<?php

namespace App\Services\DataService;

class PhotosData extends DataServiceAbstract
{
    /**
     * Set URL
     * @return string
     */
    public function setUrl(): string
    {
        return 'https://jsonplaceholder.typicode.com/photos';
    }

    public function getAll()
    {
//        return parent::getAll(); // TODO: Change the autogenerated stub

        return $this->transformer(parent::getAll());
    }

    // Removes albumID
    public function transformer($data)
    {
        foreach($data as &$item) {
            unset($item['albumId']);
        }
        return $data; // unset reference
    }


}
